### ISSUE TITLE
Is this broker suitable for thingsboard.cloud?

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/tbmq#100]
I have doubts about whether this is useful for thingsboard.cloud, and how to implement it? Or is it only for the PE version?

**Comment by dmytro-landiak** [comment]
hi @ezeroldan24!

Thank you for your interest in this regard and for raising the question. 
TBMQ can be used in the same way with thingsboard.cloud as with the TB PE version. 
thingsboard.cloud is the same PE version managed by the ThingsBoard team. 
So, if you are interested in using TBMQ with the cloud, you need to deploy TBMQ somewhere (in the cloud or on-premise) and follow the same instructions:
https://thingsboard.io/docs/mqtt-broker/user-guide/integrations/how-to-connect-thingsboard-to-tbmq/

If you have any more questions, let me know. Regards!

**Comment by dmytro-landiak** [comment]
Closing as inactive, please reopen it in case needed.
