### ISSUE TITLE
feature lack code file

### ISSUE THREAD

**Issue by huangyg1252497580** [thingsboard/tbmq#112]
**Component**

* UI
* Core
* Installation
* Generic

**Description**
Hi Dima,
When I was learning about the TBMQ project, I found that the branch 1.3.0 code was indeed missing some code files, which were in org.thingsboard.mqtt.broker.gen.queue，so  can you help me,Looking forward to your reply，thanks
**Environment**

* OS:  name and version
* TBMQ:  1.3.0
* Browser: name and version

**Comment by dmytro-landiak** [comment]
Hi @huangyg1252497580,

it seems you are referencing org.thingsboard.mqtt.broker.gen.queue package and QueueProtos class.
![image](https://github.com/thingsboard/tbmq/assets/10978307/1479700c-e3fd-445f-b6d2-7b553bd90a0b)

It is generated out of "queue.proto" file during the build.

Please execute one of the following commands from the root of the project
```
mvn generate-sources
```
to generate sources from proto file, or
```
mvn clean install -DskipTests
```
to build the whole project.

After you have done this the file will appear in your code structure.
If you have any more questions, please let me know.

**Comment by huangyg1252497580** [comment]
ok,thank you!

**Comment by huangyg1252497580** [comment]
ok ,thank you!
Now I want to package and deploy a TBMQ application through the source code, do you have a manual?

**Comment by dmytro-landiak** [comment]
I recommend following the next guide to build the project and get the packages and docker images.
https://thingsboard.io/docs/mqtt-broker/install/building-from-source/#build-local-docker-images

Then use the installation options guide to deploy where needed.
https://thingsboard.io/docs/mqtt-broker/install/installation-options/

**Comment by huangyg1252497580** [comment]
ok , thank you!

**Comment by dmytro-landiak** [comment]
Thanks for reaching out. Closing the ticket as completed.

Do not hesitate to contact me if you have any further questions. In that case, please reopen the ticket or create a new one if related to another topic.
