### ISSUE TITLE
[Feature Request] Show credentials used in session tab

### ISSUE THREAD

**Issue by Webbeh** [thingsboard/tbmq#133]
Currently, in 1.3.0, the Sessions tab shows, quite obviously, a list of sessions. This is extremely useful and helps with debugging and maintenance an awful lot.

I would like that tab to show which Credentials are used for that session (using the name of the credentials as shown in the Credentials tab).

I have got a LOT of legacy devices that have been migrated from company to company, from customer to customer, and ended up in my broker using very outdated and insecure credentials. I would love to be able to see which ones are using those deprecated credentials in the sessions view.

This is an example of what I would love to see : 
![image](https://github.com/thingsboard/tbmq/assets/1530837/bbaed8da-5486-41f7-a895-0150c0cb668f)

Those credentials names would be taken from : 
![image](https://github.com/thingsboard/tbmq/assets/1530837/494b0aed-2dd0-4733-8ffe-7ee468163d9a)

Thank you very much !

**Comment by dmytro-landiak** [comment]
hey @GOinfo-Ltd!

Thank you for the request. This is a very valid and useful feature, and we have already planned to implement this in the upcoming releases. Please, stay tuned for the updates.

Regards!
