### ISSUE TITLE
[Question] MQTTS credentials dynamic management in TBMQ?

### ISSUE THREAD

**Issue by gaizkasi** [thingsboard/tbmq#136]
**Component**
* Installation: Docker Cluster in Linux Server

**Description**
I would like to deploy MQTTS in TBMQ publications and I would like to know how I could manage MQTTS credentials configuration taking into account that device provisioning must be dynamic, that is, not using UI.

* OS:  4.19.0-26-amd64 https://github.com/thingsboard/tbmq/pull/1 SMP Debian 4.19.304-1 (2024-01-09) x86_64 GNU/Linux
* TBMQ: 1.3.0

**Comment by dmytro-landiak** [comment]
Hi @gaizkasi!

Thank you for your question. Could you please provide more details about the dynamic client credentials provisioning you aim to achieve?

Currently, if authentication is enabled on the broker, client credentials need to be pre-created to allow devices to connect. Automatic creation of credentials during device connection is not supported.

However, you can use our API to provision client credentials before the device attempts to connect, bypassing the need for the UI.

If you can provide additional details about your specific use case, I would be glad to assist further.

Regards!

**Comment by gaizkasi** [comment]
Hi @dmytro-landiak!

I mean, what I would like to have is a process in TBMQ as in the standard Thingsboard Transport where you could provide using RPC request/responses the credentials for a device:

https://thingsboard.io/docs/user-guide/device-provisioning/?mqttprovisioning=x509-certificate

![irudia](https://github.com/thingsboard/tbmq/assets/56073775/246d9f45-abab-421d-97be-f5011a5570d2)

I don't know if the API that you mention does something similar. Is that in the documentation?

Regards!

Gaizka

**Comment by dmytro-landiak** [comment]
hi @gaizkasi!

Thank you for your inquiry regarding the Device Provisioning feature. Currently, this feature is available in TB but not in TBMQ.

We understand the importance of this functionality and will consider adding it to TBMQ in future updates. However, please note that it is not on our current roadmap, so it won't be included in the immediate upcoming releases.

If you have any further questions or need assistance with other features, please feel free to reach out.

Regards!

**Comment by gaizkasi** [comment]
Thanks for all!
