### ISSUE TITLE
[Question] Possibility to relay topics to another MQTT broker?

### ISSUE THREAD

**Issue by apachler** [thingsboard/tbmq#162]
**Component**

* Generic

**Description**
Is it possible to configure some kind of relay/bridge from one broker to the other?
We have a test and prod environment. On the prod environment we have several devices
that are publishing data to the topic `edge/#` - it would be nice to have the possibility to
"mirror" those messages from the prod environment to the test environment.

The mosquitto MQTT broker supports this and calls that a bridge.
See http://www.steves-internet-guide.com/mosquitto-bridge-configuration/

**Environment**

* OS:  SLES 15
* TBMQ: 1.4.0

**Comment by dmytro-landiak** [comment]
Hi @apachler,

Thank you for your feature request!

Unfortunately, the TBMQ does not currently support a relay or bridge functionality like the one described for the Mosquitto broker. While we are not actively working on this feature at the moment, it is planned to enter development soon and will be available in one of the upcoming releases.

We appreciate your patience and will keep you updated as we make progress!

**Comment by apachler** [comment]
nice, thanks for you response!
