### ISSUE TITLE
[Question] After an update to TBMQ 2.0 I got messed up 2 new entities 

### ISSUE THREAD

**Issue by IhorYednak** [thingsboard/tbmq#186]
Hi @dmytro-landiak 
After an update to TBMQ 2.0, I can see 2 new fields:
 subscription.subscriptions
unauthorized-client.unauthorized-clients
Here are some screenshots

![image](https://github.com/user-attachments/assets/d004e578-f8fd-417f-92bb-84d36cb535ea)
![image](https://github.com/user-attachments/assets/7ccb75e1-7585-4a96-adb5-438eef6bff23)

I believe the entity names shouldn't be like this, and also there should not be an error at "unauthorized-client.unauthorized-clients" section
So I think I probably did something wrong at the ./tbmq-install-and-run.sh
Can u pls advice on what could be wrong?

Also highlighted is the piece of code that I changed according to the documentation
![image](https://github.com/user-attachments/assets/4a0fd9d1-6eba-4540-9a1a-bd30a4d929db)

Here is the redis section at docker.compose.yml
![image](https://github.com/user-attachments/assets/bd06e7e0-16f0-44fe-9752-4d0b2758e05d)

As always, thank you in advance!

**Comment by IhorYednak** [comment]
Hey @dmytro-landiak , I did not miss it running first time, but there could be an error executing it indeed.
However I did it again, here some logs from console:

wget -O tbmq-upgrade.sh https://raw.githubusercontent.com/thingsboard/tbmq/release-2.0.0/msa/tbmq/configs/tbmq-upgrade.sh &&
sudo chmod +x tbmq-upgrade.sh && ./tbmq-upgrade.sh
--2024-12-03 15:25:31--  https://raw.githubusercontent.com/thingsboard/tbmq/release-2.0.0/msa/tbmq/configs/tbmq-upgrade.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4097 (4.0K) [text/plain]
Saving to: ‘tbmq-upgrade.sh’

tbmq-upgrade.sh                                                              100%[=============================================================================================================================================================================================>]   4.00K  --.-KB/s    in 0s      

2024-12-03 15:25:31 (53.4 MB/s) - ‘tbmq-upgrade.sh’ saved [4097/4097]

[sudo] password for prdmzgateway: 
Docker Compose version is: V2
2.0.0: Pulling from thingsboard/tbmq
Digest: sha256:afc1cec150c60cade1367ab6e684671a7f9f766bc66cca183f8a36c6e92bdaa2
Status: Image is up to date for thingsboard/tbmq:2.0.0
docker.io/thingsboard/tbmq:2.0.0
Docker Compose file backup created: docker-compose.yml.bak
Trying to replace the TBMQ image version from [1.4.0] to [2.0.0]...
TBMQ image line updated in docker-compose.yml with the new version
WARN[0000] /home/prdmzgateway/docker-compose.yml: `version` is obsolete 
[+] Stopping 1/0
 ✔ Container prdmzgateway-tbmq-1  Stopped                                                                                                                                                                                                                                                                     0.0s 
WARN[0000] /home/prdmzgateway/docker-compose.yml: `version` is obsolete 
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
docker: no name set for network.
See 'docker run --help'.
WARN[0000] /home/prdmzgateway/docker-compose.yml: `version` is obsolete 
? Going to remove prdmzgateway-tbmq-1 Yes
[+] Removing 1/1
 ✔ Container prdmzgateway-tbmq-1  Removed                                                                                                                                                                                                                                                                     0.2s 
WARN[0000] /home/prdmzgateway/docker-compose.yml: `version` is obsolete 
[+] Running 1/1
 ✔ Container prdmzgateway-tbmq-1  Started

Opened the portal again, giving the same error, also corrected the redis url at /tbmq-upgrade.sh as you suggested

**Comment by dmytro-landiak** [comment]
can you execute the following commands and show me the output?

```
docker compose ps | grep "postgres" | awk '{ print $1 }'
```
Example: **downloads-postgres-1**

Put in the command below instead of `downloads-postgres-1` the returned name from the above command.

```
docker inspect -f '{{ range .NetworkSettings.Networks }}{{ .NetworkID }}{{ end }}' downloads-postgres-1
```
Example: **049d97c42572af92b538f0735ae6c000596ffcfd2cbfdef64874c6360b73eab9**

**Comment by IhorYednak** [comment]
Here what I got

prdmzgateway@prdmzgateway:~$ docker compose ps | grep "postgres" | awk '{ print $1 }'
WARN[0000] /home/prdmzgateway/docker-compose.yml: `version` is obsolete 
prdmzgateway-postgres-1
prdmzgateway@prdmzgateway:~$ docker inspect -f '{{ range .NetworkSettings.Networks }}{{ .NetworkID }}{{ end }}' prdmzgateway-postgres-1
d30a11fa1d82e826711166111960bec020042b8a56bd8c9ee8fd5f81f6769c31

**Comment by dmytro-landiak** [comment]
maybe try running the following command that should have been executed by the script. I have replaced the values to use the default ones and your network id. Pls double-check them before executing

```
docker run -it --network=d30a11fa1d82e826711166111960bec020042b8a56bd8c9ee8fd5f81f6769c31 \
      -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/thingsboard_mqtt_broker \
      -e SPRING_DATASOURCE_USERNAME=postgres \
      -e SPRING_DATASOURCE_PASSWORD=postgres \
      -e REDIS_HOST=redis \
      -e MQTT_PERSISTENT_SESSION_DEVICE_PERSISTED_MESSAGES_LIMIT=1000 \
      -v tbmq-data:/data \
      --rm \
      thingsboard/tbmq:2.0.0 upgrade-tbmq.sh
```

**Comment by IhorYednak** [comment]
Is this the expected outcome about the UnauthorizedClient?

Successfully removed device publish messages from Postgres!
Updating data from version 1.4.0 to 2.0.0 ...
Upgrade finished successfully!
[InsertUnauthorizedClientQueue] Queue polling was interrupted.
[DeleteUnauthorizedClientQueue] Queue polling was interrupted.
[LatestTimeseriesQueue] Queue polling was interrupted.
[InsertUnauthorizedClientQueue] Queue polling was interrupted.
[LatestTimeseriesQueue] Queue polling was interrupted.
[InsertUnauthorizedClientQueue] Queue polling was interrupted.
[LatestTimeseriesQueue] Queue polling was interrupted.
[DeleteUnauthorizedClientQueue] Queue polling was interrupted.
[DeleteUnauthorizedClientQueue] Queue polling was interrupted.
[TimeseriesQueue] Queue polling was interrupted.
[TimeseriesQueue] Queue polling was interrupted.
[TimeseriesQueue] Queue polling was interrupted.
Closing JPA EntityManagerFactory for persistence unit 'default'
HikariPool-1 - Shutdown initiated...
HikariPool-1 - Shutdown completed.

**Comment by dmytro-landiak** [comment]
yes the logs you show are fine and seems you upgraded successfully.

**Comment by IhorYednak** [comment]
Alright nice, yea, seems like everything now look good, thank you @dmytro-landiak
