### ISSUE TITLE
Will future versions integrate features like rule chains?  

### ISSUE THREAD

**Issue by guodaxia103** [thingsboard/tbmq#43]
**### Will future versions integrate features like rule chains?  
In this way, data parsing, data forwarding, and data storage are more convenient**

**Comment by dmytro-landiak** [comment]
Hi @guodaxia103 ,

Initially, TBMQ emerged from the requirements of enterprise clients who wanted a reliable MQTT broker capable of handling their IoT infrastructure seamlessly with connectivity to ThingsBoard PE and other applications of their usage. With the goal of offering scalability, fault tolerance, and high performance, the development team at ThingsBoard responded by crafting TBMQ as a standalone MQTT broker, distinct from the core ThingsBoard platform. This approach enabled existing enterprise clients to integrate TBMQ seamlessly into their existing IoT ecosystem.
TBMQ continued to evolve and prove its value in enterprise scenarios.  Acknowledging the demand for a scalable and performant MQTT broker within the IoT community, ThingsBoard wanted to share the benefits of TBMQ with a broader audience thus making it publicly available.
To facilitate the integration of ThingsBoard with TBMQ, the development team is diligently working on creating comprehensive guides. These guides will provide step-by-step instructions and best practices, making it easier for users to integrate the two of them. Thus users and organizations will be able to leverage the combined strengths of ThingsBoard's comprehensive IoT management tools and TBMQ's robust broker, achieving a synergistic IoT solution that maximizes connectivity, scalability, and performance.
However, as previously stated, TBMQ can operate autonomously from TB, and conversely, TB can function independently of TBMQ. This characteristic grants them the ability to address distinct requirements and cover different use cases.
For the future, we want to continue developing the TBMQ in a way that it can work both as a standalone product covering a wide range of IoT use cases and with the ability to integrate out of the box with a wide range of applications like AWS SQS, RabbitMQ, Kafka, Redis, and others.

Stay tuned for more updates.
