### ISSUE TITLE
[Feature Request] Cluster setup with AKS on Azure

### ISSUE THREAD

**Issue by amillot** [thingsboard/tbmq#62]
Dear Thingsboad Team,
I see there is a cluster setup with Kubernetes on AWS currently for tbmq.
Do you plan on releasing a cluster setup with AKS on Azure in the near future ?
We are hosting our TB PE on Azure and would like to use tbmq as our primary broker while keeping all our infra on Azure.
Thanks

**Comment by dmytro-landiak** [comment]
hi @amillot !

We will work on the documentation and scripts of a cluster setup on Azure.

**Comment by dmytro-landiak** [comment]
probably within 1-2 months.

Is your current TB PE setup done using AKS on Azure?

**Comment by amillot** [comment]
Perfect.
Yes our current TB PE was setup using the monolithic AKS setup guide.

**Comment by dmytro-landiak** [comment]
I will get back to you with more info later, thank you!

**Comment by amillot** [comment]
Alright, thank you for the quick support 👍

**Comment by amillot** [comment]
Hey, is there any news on the development and release of this particular feature ?
Kind regards

**Comment by dmytro-landiak** [comment]
@amillot, this is already in the development. I expect this to be released this or next week

**Comment by amillot** [comment]
Awesome, looking forward to the release !
Kind regards

**Comment by dmytro-landiak** [comment]
Hi @amillot, 
We are finalizing the documentation updates. I will get back to you with the link once we publish it on the site. It could be today/tomorrow.

**Comment by dmytro-landiak** [comment]
@amillot, please take a look at the AKS guide
https://thingsboard.io/docs/mqtt-broker/install/cluster/azure-cluster-setup/

p.s. Note, that you may face some issues with the site, it is cache cache-related issue that should be fixed quite soon.

**Comment by amillot** [comment]
Awesome thanks for the quick work, will get back to you if we get any issues while deploying the broker !

**Comment by dmytro-landiak** [comment]
@amillot, sure!

pls open another issue if you face any problems or have any questions regarding the deployment.
I am closing this one as the feature request is done.
