### ISSUE TITLE
[Feature Request] - Create user password or activate without smpt server

### ISSUE THREAD

**Issue by jot4p** [thingsboard/tbmq#72]
Hi, 

How I can create a new user and create or set password without smpt server ? 

Best Regards

**Comment by dmytro-landiak** [comment]
hi @jot4p,

You can create a new user on the following page when you log in with the default credentials.

![image](https://github.com/thingsboard/tbmq/assets/10978307/df75f163-9dbc-4b9d-8e4b-dea086cb3cff)

The new user will be created with the default password 'sysadmin'.

Then on the first login of this new user, you will be asked to change the default password.
Or you can do this on this page:
![image](https://github.com/thingsboard/tbmq/assets/10978307/cf6cd7bf-8158-4f7e-9bd0-c8f04eb3f489)

**Comment by jot4p** [comment]
ok, the secret is your default password :)
