### ISSUE TITLE
[Question] how do I use TBMQ with TBPE on Docker?

### ISSUE THREAD

**Issue by skewty** [thingsboard/tbmq#89]
I checked https://thingsboard.io/docs/user-guide/install/pe/docker/ but it doesn't even mention TBPE.

I read the source code of the python IoT GW and it seems to have shared / mapped-at-runtime topics such as "v1/devices/me" and also: "v1/gateway".

I'd like to use TBMQ with TBPE so the MQTT broker can be shared with other services (on-prem).

**Comment by dmytro-landiak** [comment]
hey @skewty !

Thanks for reaching out with the question.
I would recommend reviewing the following article about how to connect TBMQ with TB PE.
https://thingsboard.io/docs/mqtt-broker/user-guide/integrations/how-to-connect-thingsboard-to-tbmq/

Additionally, review the installation options for TBMQ:
https://thingsboard.io/docs/mqtt-broker/install/installation-options/

In case you have any more questions, let me know. Regards!

**Comment by dmytro-landiak** [comment]
@skewty, your understanding is correct. For now, we are concentrating on developing TBMQ as an independent platform but we aim to create a more sophisticated solution for the integration of TBMQ and Thingsboard (ce/pe) in the future. 
For now, could I ask you about the feedback on why you wanted to have a TBMQ as a replacement for build-in MQTT transport inside Thingssboard? Is there anything that blocks you from covering your use cases/requirements by using TB PE only (as I understand that using TBMQ and connecting it to TB PE through the MQTT integration is not what you want to use)?

**Comment by dmytro-landiak** [comment]
@skewty, thank you for the feedback. This will be discussed internally to be able to improve our services and support.

If you have any more questions or if I can help you with something else somehow, please let me know.
